Switch how magic-flash is called
Better to see whats going on that report it

diff --git a/nethunter/META-INF/com/google/android/update-magisk b/nethunter/META-INF/com/google/android/update-magisk
--- a/nethunter/META-INF/com/google/android/update-magisk
+++ b/nethunter/META-INF/com/google/android/update-magisk
@@ -19,18 +19,22 @@ do_flash() {
   ## #1 - Down side the output isn't formatted
   #sh $TMP/tools/magic-flash.sh $KERNEL 2>&1 || abort "! magic-flash.sh failed"
 
-  ## #2 - Down side the output isn't in real time
-  OUT=$( sh $TMP/tools/magic-flash.sh $KERNEL 2>&1 )
-  ret=$?
-  if [ "$ret" -eq 0 ]; then
-    ## Replace ui_print, indent output (to signal its a script) and remove empty lines
-    echo "${OUT}" | awk 'gsub(/ui_print /," ") && !/^ $/'
-  else
-    echo "${OUT}"   # Will be much more verbose
-    abort "! magic-flash.sh failed: $ret"
-  fi
+  ## #2 - Down side not sure if it exits cleanly
+  ## Replace ui_print, indent output (to signal its a script) and remove empty lines
+  sh $TMP/tools/magic-flash.sh $KERNEL | awk 'gsub(/ui_print /," ") && !/^ $/'
 
-  ## #3 - Can't do this bash trick, as using sh (shell)
+  ## #3 - Down side the output isn't in real time
+  #OUT=$( sh $TMP/tools/magic-flash.sh $KERNEL 2>&1 )
+  #ret=$?
+  #if [ "$ret" -eq 0 ]; then
+  #  ## Replace ui_print, indent output (to signal its a script) and remove empty lines
+  #  echo "${OUT}" | awk 'gsub(/ui_print /," ") && !/^ $/'
+  #else
+  #  echo "${OUT}"   # Will be much more verbose
+  #  abort "! magic-flash.sh failed: $ret"
+  #fi
+
+  ## #4 - Can't do this bash trick, as using sh (shell)
   ## Replace ui_print, indent output (to signal its a script) and remove empty lines
   #sh $TMP/tools/magic-flash.sh $KERNEL 2>&1 | awk 'gsub(/ui_print /," ") && !/^ $/'   # Spawn a new session (aka using sh), don't do it in the current session
   #ret=${PIPESTATUS[0]}   # We want magic-flash.sh exit code, not awk!
