fix some mistakes and exit status

diff --git a/boot-patcher/META-INF/com/google/android/update-binary b/boot-patcher/META-INF/com/google/android/update-binary
--- a/boot-patcher/META-INF/com/google/android/update-binary
+++ b/boot-patcher/META-INF/com/google/android/update-binary
@@ -199,7 +199,11 @@ chmod +x env
 #we need to mount system here as it is disabled in update-binary-anykernel
 print "- Mounting partitions for Boot-Patching"
 mount_all;
-print "- Partitions mounted"
+if [ $? != 0 ]; then 
+abort "Cannot mount system partition read/write. Please mount '/system' manually and try again" 
+else 
+print "partitions mounted." 
+fi
 setperm 0755 0755 tools
 
 if [ "$ZIPFILE" ]; then 
