Source vs sh
- Where possible used source, and not sh (That way, variables and functions can be passed - thus less duplicate code)
- Drop shebangs if sourcing script
- A few fixes are not included (exit vs return), which will come when the scripts are fresh
  - freespace.sh
  - set-wallpaper.sh
  - boot-patcher
- Few other misc fixes included - will touch on them in a later commit. eg:
  - busybox's unzip not having -j
  - install-chroot.sh - check more paths
  - Fixing terms

diff --git a/boot-patcher/META-INF/com/google/android/update-binary b/boot-patcher/META-INF/com/google/android/update-binary
--- a/boot-patcher/META-INF/com/google/android/update-binary
+++ b/boot-patcher/META-INF/com/google/android/update-binary
@@ -26,17 +26,17 @@ cleanup() {
   [ "$ZIPFILE" ] && {
    rm /tmp/console
   }
-  cd $(dirname $tmp)
-  rm -rf $tmp
+  cd $(dirname $TMP)
+  rm -rf $TMP
 }
 
 install() {
-  setperm "$2" "$3" "$tmp$1"
+  setperm "$2" "$3" "$TMP$1"
   if [ "$4" ]; then
-    cp -r "$tmp$1" "$(dirname "$4")/"
+    cp -r "$TMP$1" "$(dirname "$4")/"
     return
   fi
-  cp -r "$tmp$1" "$(dirname "$1")/"
+  cp -r "$TMP$1" "$(dirname "$1")/"
 }
 
 extract() {
@@ -52,9 +52,9 @@ setperm() {
 }
 
 get_bb() {
-  cd $tmp/tools
+  cd $TMP/tools/
   BB_latest=$( (ls -v busybox_nh-* 2>/dev/null || ls busybox_nh-*) | tail -n 1)
-  BB=$tmp/tools/$BB_latest # Use NetHunter BusyBox from tools
+  BB=$TMP/tools/$BB_latest # Use NetHunter BusyBox from ./arch/<arch>/tools/
   chmod 0755 $BB # Make BusyBox executable
   echo $BB
   cd - >/dev/null
@@ -63,7 +63,7 @@ get_bb() {
 install_recovery_bb() {
   ## To identify the latest BusyBox version, we need the command "ls -v" which is not supported by all TWRP versions
   ## We will pick the best available BusyBox version and use that to run "ls -v" to pick the latest version for the recovery partition
-  cd $tmp/tools
+  cd $TMP/tools
 
   ## Try to pick the latest version of BusyBox, if "ls -v" is not supported by the recovery then make an educated guess for a later version
   recovery_bb=$( (ls -v busybox_nh-* 2>/dev/null || ls busybox_nh-*) | tail -n 1 )
@@ -97,7 +97,8 @@ fi
 
 test "$ANDROID_ROOT" || ANDROID_ROOT=/system
 SYSTEM="/system"
-tmp=/tmp/nethunter/boot-patcher
+TMPDIR=/dev/tmp
+TMP=$TMPDIR/nethunter/boot-patcher # This is fixed path due to ./installer/, as that extracts and needs to know of this path
 
 if [ "$ZIPFILE" ]; then
   print ""
@@ -133,7 +134,7 @@ fi
   #print "$prefix Installer unpacked"
 }
 
-cd "$tmp"
+cd "$TMP"
 
 print "$prefix Loading environment"
 chmod +x env
@@ -144,19 +145,19 @@ setperm 0755 0755 tools
 
 print "$prefix Setting up BusyBox"
 BB=$(get_bb)
-# Install BusyBox applets if they haven't been installed by the NetHunter installer already
-[ -e /tmp/nethunter/tools/busybox_tmp ] || install_recovery_bb
 
 if [ "$ZIPFILE" ]; then
   print "$prefix Running BusyBox installer"
   sh tools/install-busybox.sh #run only
   #print "$prefix Done running BusyBox installer"
+## Install BusyBox applets if they haven't been installed by the NetHunter already
+[ -e $TMPDIR/nethunter/tools/busybox_tmp ] || install_recovery_bb
 
   print "$prefix Running kernel installer"
 else
   print "$prefix Running boot image patcher"
 fi
-sh "META-INF/com/google/android/update-binary-anykernel" || abort
+sh "META-INF/com/google/android/update-binary-anykernel" || abort "boot patcher failed"
 #print "$prefix Boot patcher done"
 
 print "$prefix Boot image patching complete"
diff --git a/nethunter/META-INF/com/google/android/update-magisk b/nethunter/META-INF/com/google/android/update-magisk
--- a/nethunter/META-INF/com/google/android/update-magisk
+++ b/nethunter/META-INF/com/google/android/update-magisk
@@ -1,28 +1,7 @@
-## Kali NetHunter installation script for Magisk (BOOTMODE=true)
+## [Magisk] [nethunter] [This is sourced, not a standalone script]
+## Kali NetHunter installation script for Magisk
 ## REF: https://github.com/topjohnwu/Magisk/blob/master/scripts/update_binary.sh
 ##      https://github.com/topjohnwu/Magisk/blob/master/scripts/util_functions.sh
-
-file_getprop() {
-  grep "^$2" "$1" | head -n1 | cut -d= -f2-
-}
-
-set_perm() {
-  chown $2:$3 $1 || return 1
-  chmod $4 $1 || return 1
-  CON=$5
-  [ -z $CON ] && CON=u:object_r:system_file:s0
-  chcon $CON $1 || return 1
-}
-
-set_perm_recursive() {
-  find $1 -type d 2>/dev/null | while read dir; do
-    set_perm $dir $2 $3 $4 $6
-  done
-
-  find $1 -type f -o -type l 2>/dev/null | while read file; do
-    set_perm $file $2 $3 $5 $6
-  done
-}
 
 symlink() {
   ln -sf "$1" "$2" 2>/dev/null
@@ -239,7 +218,10 @@ do_install() {
 do_flash() {
   ui_print "* Found Kali kernel to be installed: $KERNEL"
   unzip -p "$ZIPFILE" "$KERNEL" > "$KERNEL"
-  $MAGISKBB sh $TMP/tools/magic-flash.sh $KERNEL | awk '!/    ui_print/ && !/inflating/ && gsub(/ui_print/,"")'   # Don't use sh over source
+  out=$(sh $TMP/tools/magic-flash.sh $KERNEL)    # Spawn a new session (aka using sh), don't in current session (able to pass variables/functions)
+  ret=$?   # We want magic-flash.sh exit code, not awk!
+  echo "$out" | awk 'gsub(/ui_print /," ") && !/^ $/' # Replace ui_print, to indent output (to signal its a script), remove empty lines and banner
+  [ "$ret" -eq 0 ] || abort "! magic-flash.sh failed"
 }
 
 flash_kernel() {
@@ -275,33 +257,7 @@ do_chroot() {
   }
 }
 
-require_new_magisk() {
-  echo "*******************************"
-  echo " Please install Magisk v20.4+! "
-  echo "*******************************"
-  exit 1
-}
-
 #------------------------------------------------------------------------------
-
-#<REF: ./scripts/module_installer.sh>
-#################
-# Initialization
-#################
-umask 022
-
-#########################
-# Load util_functions.sh
-#########################
-OUTFD=$2
-ZIPFILE=$3
-
-mount /data 2>/dev/null
-
-[ -f /data/adb/magisk/util_functions.sh ] || require_new_magisk
-source /data/adb/magisk/util_functions.sh
-[ $MAGISK_VER_CODE -lt 20400 ] && require_new_magisk
-#</ REF: ./scripts/module_installer.sh>
 
 #<REF: ./scripts/util_functions.sh>
 #########################
@@ -388,7 +344,7 @@ cd $TMPDIR
 
 # Source custom installer functions and configuration
 unzip -jo "$ZIPFILE" module.prop -d $TMPDIR >&2
-MODID=$(file_getprop module.prop id)
+#MODID=$(file_getprop module.prop id) # Alt: MODID=$(grep_prop id $TMPDIR/module.prop)
 
 ## Extract the ZIP
 ui_print "* Unpacking ZIP"
@@ -494,7 +450,7 @@ pm install -g $TMP/data/app/NetHunterStorePrivilegedExtension.apk &>/dev/null
 
 ## Install BusyBox
 ui_print "* Setting up BusyBox"
-[ -f $TMP/tools/install-busybox-magisk.sh ] && source $TMP/tools/install-busybox-magisk.sh   # Don't use sh over source
+source $TMP/tools/install-busybox.sh || abort "! install-busybox.sh"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
 #print "* Done installing BusyBox"
 
 #------------------------------------------------------------------------------
diff --git a/nethunter/META-INF/com/google/android/update-recovery b/nethunter/META-INF/com/google/android/update-recovery
--- a/nethunter/META-INF/com/google/android/update-recovery
+++ b/nethunter/META-INF/com/google/android/update-recovery
@@ -1,4 +1,5 @@
-## Kali NetHunter installation script for recovery/TWRP (BOOTMODE=false)
+## [Recovery/TWRP] [nethunter] [This is sourced, not a standalone script]
+## Kali NetHunter installation script for recovery/TWRP
 ##
 ## Troubleshoot: $ adb shell 'tail -f /tmp/recovery.log'
 
@@ -20,17 +21,17 @@ cleanup() {
   [ "$ZIPFILE" ] && {
    rm /tmp/console
   }
-  cd $(dirname $TMPDIR)
-  rm -rf $TMPDIR
+  cd $(dirname $TMP)
+  rm -rf $TMP
 }
 
 install() {
-  setperm "$2" "$3" "$TMPDIR$1"
+  setperm "$2" "$3" "$TMP$1"
   if [ "$4" ]; then
-    cp -r "$TMPDIR$1" "$(dirname "$4")/"
+    cp -r "$TMP$1" "$(dirname "$4")/"
     return
   fi
-  cp -r "$TMPDIR$1" "$(dirname "$1")/"
+  cp -r "$TMP$1" "$(dirname "$1")/"
 }
 
 # installapp_user "App Name" "appfile.apk" "play.store.package.name"
@@ -57,15 +58,15 @@ installapp_user() {
 
   #print "* Installing $1 to $installto"
   print "*** Installing $1"
-  cp -f "$TMPDIR/data/app/$1" "$installto" && return 0
+  cp -f "$TMP/data/app/$1" "$installto" && return 0
   print "* Failed to install $1!" && return 1
 }
 
 installapp_system() {
-  check_freespace $TMPDIR/data/app/
+  check_freespace $TMP/data/app/
   print "*** Installing $1"
   mkdir -p ${SYSTEM}/${3:-app}/$2/
-  cp -f $TMPDIR/data/app/$1 ${SYSTEM}/${3:-app}/$2/ && return 0
+  cp -f $TMP/data/app/$1 ${SYSTEM}/${3:-app}/$2/ && return 0
   print "* Failed to install $1!" && return 1
 }
 
@@ -308,9 +309,9 @@ restore_env() {
 }
 
 get_bb() {
-  cd $TMPDIR/tools
+  cd $TMP/tools/
   BB_latest=$( (ls -v busybox_nh-* 2>/dev/null || ls busybox_nh-*) | tail -n 1)
-  BB=$TMPDIR/tools/$BB_latest # Use NetHunter BusyBox from tools
+  BB=$TMP/tools/$BB_latest # Use NetHunter BusyBox from ./arch/<arch>/tools/
   chmod 0755 $BB # Make BusyBox executable
   echo $BB
   cd - >/dev/null
@@ -319,7 +320,7 @@ get_bb() {
 install_recovery_bb() {
   ## To identify the latest BusyBox version, we need the command "ls -v" which is not supported by all TWRP versions
   ##   We will pick the best available BusyBox version and use that to run "ls -v" to pick the latest version for the recovery partition
-  cd $TMPDIR/tools
+  cd $TMP/tools/
 
   ## Try to pick the latest version of BusyBox, if "ls -v" is not supported by the recovery then make an educated guess for a later version
   recovery_bb=$( (ls -v busybox_nh-* 2>/dev/null || ls busybox_nh-*) | tail -n 1 )
@@ -364,21 +365,10 @@ check_freespace() {
 supersu="auto"
 ## End build generated variables
 
-if [ "$3" ]; then
-  ZIPFILE=$3
-  console=/proc/$$/fd/$2
-  # Write the location of the console buffer to /tmp/console for other scripts to use
-  echo "$console" > /tmp/console
-else
-  [ -f /tmp/console ] && console=$(cat /tmp/console)
-  [ "$console" ] || console=/proc/$$/fd/1
-fi
+test "$ANDROID_ROOT" || ANDROID_ROOT="$SYSTEM"
+bootpatcher_tmp=$TMP/boot-patcher
+export home=$bootpatcher_tmp
 
-test "$ANDROID_ROOT" || ANDROID_ROOT=/system
-tmp=/tmp/nethunter
-patchtmp=$TMPDIR/boot-patcher
-export home=$patchtmp
-sutmp=/tmp/supersu
 
 #------------------------------------------------------------------------------
 
@@ -386,11 +376,11 @@ sutmp=/tmp/supersu
 ### Unpack the installer (everything but "kalifs-*")
 #[ "$ZIPFILE" ] && {
 #  print "* Unpacking the installer"
-#  extract "$ZIPFILE" "$TMPDIR" "kalifs-*"
+#  extract "$ZIPFILE" "$TMP" "kalifs-*"
 #  #print "* Installer unpacked"
 #}
 
-cd "$TMPDIR"
+cd "$TMP"
 
 print "* Loading environment"
 #chmod +x env
@@ -437,7 +427,7 @@ progress 0.1
 }
 
 print "* Running legacy Kali NetHunter version script" # Checking for previous versions of Kali NetHunter
-sh tools/previous-install.sh
+source "$TMP/tools/previous-install.sh" || abort "Legacy Kali NetHunter failed"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
 #print "* Done checking for previous versions"
 
 progress 0.2
@@ -453,7 +443,7 @@ print "*** SDK Version: $SDK"
 
 [ -f supersu.zip ] && {
   print "* Extracting SuperSU.zip"
-  extract supersu.zip "$sutmp"
+  extract supersu.zip "$supersu_tmp"
 
   progress 0.3
 
@@ -461,7 +451,7 @@ print "*** SDK Version: $SDK"
   if [ $SDK -ge 29 ]; then
     print "Warning: Warning: SuperSU is EOL and only really works on Android Pie (9) or lower"
   fi
-  sh tools/install-su.sh "$sutmp" "$supersu"
+  source "$TMP/tools/install-su.sh" || abort "SuperSU failed"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
   #print "* Done installing SuperSU"
 }
 
@@ -473,7 +463,7 @@ progress 0.4
 ##   So we install as system apps (/system)
 if [ $SDK -ge 26 ]; then
   ## Apps in /system
-  check_freespace $TMPDIR/data/app/ "True"
+  check_freespace $TMP/data/app/ "True"
   print "* Installing apps (via system):"
   installapp_system "NetHunter.apk" "com.offsec.nethunter"
   installapp_system "NetHunterTerminal.apk" "com.offsec.nhterm"       # NetHunter.apk depends on it
@@ -556,12 +546,12 @@ progress 0.5
 [ -f tools/freespace.sh ] && {
   print "* Running freespace script" # Check for freespace
   # This actually runs twice when the NetHunter kernel zip is included
-  sh tools/freespace.sh || abort "Not enough free space on ${SYSTEM} to continue!"
+  source "$TMP/tools/freespace.sh" || abort "Not enough free space on ${SYSTEM} to continue!"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
   #print "* Done checking freespace"
 }
 
 print "* Running BusyBox installer script"
-sh tools/install-busybox.sh
+source "$TMP/tools/install-busybox.sh" || abort "BusyBox failed"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
 #print "* Done running BusyBox installer"
 
 progress 0.6
@@ -570,7 +560,7 @@ progress 0.6
 
 [ -d wallpaper ] && {
   print "* Running Kali NetHunter wallpaper script" # Installing Kali NetHunter wallpaper
-  sh tools/setwallpaper.sh
+  source "$TMP/tools/set-wallpaper.sh" || abort "Set wallpaper failed"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
   #print "* Done installing wallpaper"
 }
 
@@ -647,10 +637,10 @@ progress 0.8
 
 #------------------------------------------------------------------------------
 
-[ -d "$patchtmp" ] && {
-  print "* Running kernel installer script"
-  sh "$patchtmp/META-INF/com/google/android/update-binary"
-  #print "* Done running kernel installer"
+[ -d "$bootpatcher_tmp" ] && {
+  print "* Running boot-patcher script"
+  sh "$bootpatcher_tmp/META-INF/com/google/android/update-binary" || abort "Boot-Patcher script failed"   # As it can be its own item, not using source
+  #print "* Done running boot-patcher"
 
   print "* Setting environment"
   # Setup environment again (all are restored by boot-patcher)
@@ -662,7 +652,7 @@ progress 0.9
 #------------------------------------------------------------------------------
 
 print "* Running Kali chroot installer script"
-sh "$TMPDIR/tools/install-chroot.sh" "$ZIPFILE"
+source "$TMP/tools/install-chroot.sh" || abort "Chroot script failed"   # Don't spawn a new session (aka using sh), do in current session (able to pass variables/functions)
 #print "* Done running Kali chroot installer"
 
 print "* Restoring environment"
