Improve uninstaller mount logic

diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -36,8 +36,7 @@ cleanup() {
 
 mount() {
   mountpoint -q "$1" || /sbin/busybox mount -o rw "$1" || abort "Unable to mount $1 as rw!"
-  >> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1"
-  >> "$1/.rw" && return || abort "Unable to write to $1!"
+  >> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1" || abort "Unable to write to $1!"
 }
 
 if [ "$3" ]; then
