Consistency: Tabs to spaces

diff --git a/uninstaller/META-INF/com/google/android/update-binary b/uninstaller/META-INF/com/google/android/update-binary
--- a/uninstaller/META-INF/com/google/android/update-binary
+++ b/uninstaller/META-INF/com/google/android/update-binary
@@ -2,43 +2,43 @@
 # Kali NetHunter uninstaller (does not currently do anything useful, anyone wanna take it on?)
 
 [ "$3" ] && {
-	zip=$3
-	console=/proc/$$/fd/$2
-	# write the location of the console buffer to /tmp/console for other scripts to use
-	echo "$console" > /tmp/console
+  zip=$3
+  console=/proc/$$/fd/$2
+  # write the location of the console buffer to /tmp/console for other scripts to use
+  echo "$console" > /tmp/console
 } || {
-	console=$(cat /tmp/console)
-	[ "$console" ] || console=/proc/$$/fd/1
+  console=$(cat /tmp/console)
+  [ "$console" ] || console=/proc/$$/fd/1
 }
 
 print() {
-	echo "ui_print $1" > $console
-	echo
+  echo "ui_print $1" > $console
+  echo
 }
 
 abort() {
-	[ "$1" ] && {
-		print "Error: $1"
-		print "Aborting..."
-	}
-	cleanup
-	print "Failed to uninstall!"
-	exit 1
+  [ "$1" ] && {
+    print "Error: $1"
+    print "Aborting..."
+  }
+  cleanup
+  print "Failed to uninstall!"
+  exit 1
 }
 
 cleanup() {
-	rm /system/.rw
-	rm /data/.rw
+  rm /system/.rw
+  rm /data/.rw
 
-	umount /system
+  umount /system
 
-	[ "$zip" ] && rm /tmp/console
+  [ "$zip" ] && rm /tmp/console
 }
 
 mount() {
-	mountpoint -q "$1" || /sbin/busybox mount -o rw "$1" || abort "Unable to mount $1 as rw!"
-	>> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1"
-	>> "$1/.rw" && return || abort "Unable to write to $1!"
+  mountpoint -q "$1" || /sbin/busybox mount -o rw "$1" || abort "Unable to mount $1 as rw!"
+  >> "$1/.rw" && return || /sbin/busybox mount -o remount,rw "$1"
+  >> "$1/.rw" && return || abort "Unable to write to $1!"
 }
 
 print "***********************"
@@ -50,38 +50,38 @@ mount /data
 
 # Remove added firmware (folder would only exist if you installed NetHunter)
 [ -d "/system/etc/firmware/rtlwifi" ] && {
-	print "@Removing Firmware";
-	rm -rf /system/etc/firmware/rtlwifi
-	rm -rf /system/etc/firmware/zd1211
-	rm -f /system/etc/firmware/ar9170-1.fw
-	rm -f /system/etc/firmware/ar9170-2.fw
-	rm -f /system/etc/firmware/carl9170.fw
-	rm -f /system/etc/firmware/htc_7010.fw
-	rm -f /system/etc/firmware/rt73.bin
-	rm -f /system/etc/firmware/rt2561.bin
-	rm -f /system/etc/firmware/rt2860.bin
-	rm -f /system/etc/firmware/rt2870.bin
-	rm -f /system/etc/firmware/rt3070.bin
+  print "@Removing Firmware";
+  rm -rf /system/etc/firmware/rtlwifi
+  rm -rf /system/etc/firmware/zd1211
+  rm -f /system/etc/firmware/ar9170-1.fw
+  rm -f /system/etc/firmware/ar9170-2.fw
+  rm -f /system/etc/firmware/carl9170.fw
+  rm -f /system/etc/firmware/htc_7010.fw
+  rm -f /system/etc/firmware/rt73.bin
+  rm -f /system/etc/firmware/rt2561.bin
+  rm -f /system/etc/firmware/rt2860.bin
+  rm -f /system/etc/firmware/rt2870.bin
+  rm -f /system/etc/firmware/rt3070.bin
 }
 
 [ -d "/system/priv-app/NetHunter" ] && {
-	print "@Removing NetHunter.apk"
-	rm -rf /system/priv-app/NetHunter
+  print "@Removing NetHunter.apk"
+  rm -rf /system/priv-app/NetHunter
 }
 
 [ -d "/system/priv-app/NetHunter-Terminal" ] && {
-	print "@Removing Term-nh.apk"
-	rm -rf /system/priv-app/NetHunter-Terminal
+  print "@Removing Term-nh.apk"
+  rm -rf /system/priv-app/NetHunter-Terminal
 }
 
 [ -d "/system/priv-app/NetHunter-VNC" ] && {
-	print "@Removing VNC-nh.apk"
-	rm -rf /system/priv-app/NetHunter-VCN
+  print "@Removing VNC-nh.apk"
+  rm -rf /system/priv-app/NetHunter-VCN
 }
 
 [ -d "/data/data/com.offsec.nethunter" ] && {
-	print "@Removing NetHunter chroot/data"
-	rm -rf /data/data/com.offsec.nethunter
+  print "@Removing NetHunter chroot/data"
+  rm -rf /data/data/com.offsec.nethunter
 }
 
 cleanup
diff --git a/update/META-INF/com/google/android/update-binary b/update/META-INF/com/google/android/update-binary
--- a/update/META-INF/com/google/android/update-binary
+++ b/update/META-INF/com/google/android/update-binary
@@ -96,13 +96,13 @@ supersu=auto
 ## end build generated variables
 
 if [ "$3" ]; then
-	ZIPFILE=$3
-	console=/proc/$$/fd/$2
-	# write the location of the console buffer to /tmp/console for other scripts to use
-	echo "$console" > /tmp/console
+  ZIPFILE=$3
+  console=/proc/$$/fd/$2
+  # write the location of the console buffer to /tmp/console for other scripts to use
+  echo "$console" > /tmp/console
 else
-	console=$(cat /tmp/console)
-	[ "$console" ] || console=/proc/$$/fd/1
+  console=$(cat /tmp/console)
+  [ "$console" ] || console=/proc/$$/fd/1
 fi
 
 test "$ANDROID_ROOT" || ANDROID_ROOT=/system
@@ -112,22 +112,22 @@ export home=$patchtmp
 sutmp=/tmp/supersu
 
 progress() {
-	echo "set_progress $1" > "$console"
+  echo "set_progress $1" > "$console"
 }
 
 print() {
-	echo "ui_print ${1:- }" > "$console"
-	echo
+  echo "ui_print ${1:- }" > "$console"
+  echo
 }
 
 abort() {
-	[ "$1" ] && {
-		print "Error: $1"
-		print "Aborting..."
-	}
-	restore_env
-	print "Failed to install Kali NetHunter!"
-	exit 1
+  [ "$1" ] && {
+    print "Error: $1"
+    print "Aborting..."
+  }
+  restore_env
+  print "Failed to install Kali NetHunter!"
+  exit 1
 }
 
 cleanup() {
@@ -139,56 +139,56 @@ cleanup() {
 }
 
 install() {
-	setperm "$2" "$3" "$tmp$1"
-	if [ "$4" ]; then
-		cp -r "$tmp$1" "$(dirname "$4")/"
-		return
-	fi
-	cp -r "$tmp$1" "$(dirname "$1")/"
+  setperm "$2" "$3" "$tmp$1"
+  if [ "$4" ]; then
+    cp -r "$tmp$1" "$(dirname "$4")/"
+    return
+  fi
+  cp -r "$tmp$1" "$(dirname "$1")/"
 }
 
 # installapp "App Name" "appfile.apk" "play.store.package.name"
 # -> if the app package is found in the play store app database, then don't install it
 installapp() {
-	installto=/data/app/
-	if [ "$3" ]; then
-		for appdir in "/data/app/$3-"*; do
-			[ -d "$appdir" ] || continue
-			echo "Found app directory: $appdir"
-			if [ ! -f /data/data/com.android.vending/databases/localappstate.db ]; then
-				echo "Could not find Play Store app database!"
-			# this should also catch paid/alternative versions if they are suffixed
-			elif strings /data/data/com.android.vending/databases/localappstate.db | grep -q "^$3"; then
-				rm -f "/data/app/$2"
-				print "- Found Play Store installed $1"
-				return 0
-			fi
-			rm -f "/data/app/$2"
-			installto=$appdir/base.apk
-			break
-		done
-	fi
-	echo "Installing $1 to $installto"
-	print "- Installing $1"
-	cp -f "$tmp/data/app/$2" "$installto" && return 0
-	print "- Failed to install $1!" && return 1
+  installto=/data/app/
+  if [ "$3" ]; then
+    for appdir in "/data/app/$3-"*; do
+      [ -d "$appdir" ] || continue
+      echo "Found app directory: $appdir"
+      if [ ! -f /data/data/com.android.vending/databases/localappstate.db ]; then
+        echo "Could not find Play Store app database!"
+      # this should also catch paid/alternative versions if they are suffixed
+      elif strings /data/data/com.android.vending/databases/localappstate.db | grep -q "^$3"; then
+        rm -f "/data/app/$2"
+        print "- Found Play Store installed $1"
+        return 0
+      fi
+      rm -f "/data/app/$2"
+      installto=$appdir/base.apk
+      break
+    done
+  fi
+  echo "Installing $1 to $installto"
+  print "- Installing $1"
+  cp -f "$tmp/data/app/$2" "$installto" && return 0
+  print "- Failed to install $1!" && return 1
 }
 
 extract() {
-	rm -rf "$2"
-	mkdir -p "$2"
-	unzip -o "$1" -d "$2" -x "$3" ||
-		abort "Unable to extract! The zip may be corrupt or your device may not have enough RAM to proceed. Consider using a smaller installer if it is available."
+  rm -rf "$2"
+  mkdir -p "$2"
+  unzip -o "$1" -d "$2" -x "$3" ||
+    abort "Unable to extract! The zip may be corrupt or your device may not have enough RAM to proceed. Consider using a smaller installer if it is available."
 }
 
 setperm() {
-	find "$3" -type d -exec chmod "$1" {} \;
-	find "$3" -type f -exec chmod "$2" {} \;
+  find "$3" -type d -exec chmod "$1" {} \;
+  find "$3" -type f -exec chmod "$2" {} \;
 }
 
 symlink() {
-	rm "$2"
-	ln -s "$1" "$2"
+  rm "$2"
+  ln -s "$1" "$2"
 }
 
 setup_mountpoint() {
@@ -430,8 +430,8 @@ print "####  ############# NetHunter ####################"
 
 # Unpack the installer
 [ "$ZIPFILE" ] && {
-	print "Unpacking the installer..."
-	extract "$ZIPFILE" "$tmp" "kalifs-*"
+  print "Unpacking the installer..."
+  extract "$ZIPFILE" "$tmp" "kalifs-*"
 }
 cd "$tmp"
 
@@ -466,7 +466,7 @@ SYSTEM="/system"
 progress 0.1
 
 [ -d /data/data ] || {
-	abort "Your data partition appears to be empty. Please complete the Android setup wizard before installing Kali NetHunter!"
+  abort "Your data partition appears to be empty. Please complete the Android setup wizard before installing Kali NetHunter!"
 }
 
 
@@ -476,12 +476,12 @@ sh tools/previnstall.sh
 progress 0.2
 
 [ -f supersu.zip ] && {
-	print "Extracting SuperSU zip..."
-	extract supersu.zip "$sutmp"
+  print "Extracting SuperSU zip..."
+  extract supersu.zip "$sutmp"
 
-	progress 0.3
+  progress 0.3
 
-	sh tools/installsu.sh "$sutmp" "$supersu"
+  sh tools/installsu.sh "$sutmp" "$supersu"
 
 }
 
@@ -543,8 +543,8 @@ mkdir -p ${SYSTEM}/priv-app/NetHunterStorePrivilegedExtension
 cp $tmp/data/app/NetHunterStorePrivilegedExtension.apk ${SYSTEM}/priv-app/NetHunterStorePrivilegedExtension/
 if [ $SDK -ge 26 ]
 then
-	mkdir ${SYSTEM}/etc/permissions 
-	chmod 755 ${SYSTEM}/etc/permissions 
+  mkdir ${SYSTEM}/etc/permissions
+  chmod 755 ${SYSTEM}/etc/permissions
         [ -f system/etc/permissions/com.offsec.nethunter.store.privileged.xml ] && {
             install "/system/etc/permissions/com.offsec.nethunter.store.privileged.xml" 0755 0644 "${SYSTEM}/etc/permissions/com.offsec.nethunter.store.privileged.xml"
         }
@@ -555,7 +555,7 @@ print "Done installing apps"
 progress 0.5
 
 [ -f tools/freespace.sh ] && {
-	# This actually runs twice when the NetHunter kernel zip is included
+  # This actually runs twice when the NetHunter kernel zip is included
  sh tools/freespace.sh || abort "Not enough free space on ${SYSTEM} to continue!"
  
 }
@@ -566,66 +566,66 @@ sh tools/installbusybox.sh
 progress 0.6
 
 [ -d wallpaper ] && {
-	print "Installing NetHunter wallpaper"
-	sh wallpaper/setwallpaper.sh
+  print "Installing NetHunter wallpaper"
+  sh wallpaper/setwallpaper.sh
 }
 
 [ -f system/media/bootanimation.zip ] && {
-	print "Installing NetHunter boot animation"
-	install "/system/media/bootanimation.zip" 0755 0644 "${SYSTEM}/media/bootanimation.zip"
+  print "Installing NetHunter boot animation"
+  install "/system/media/bootanimation.zip" 0755 0644 "${SYSTEM}/media/bootanimation.zip"
 }
 
 progress 0.7
 
 [ -d system/etc/nano ] && {
-	print "Copying nano highlights to ${SYSTEM}/etc/nano"
-	install "/system/etc/nano" 0755 0644 "${SYSTEM}/etc/nano" 
+  print "Copying nano highlights to ${SYSTEM}/etc/nano"
+  install "/system/etc/nano" 0755 0644 "${SYSTEM}/etc/nano"
 }
 
 [ -d system/etc/terminfo ] && {
-	print "Copying terminfo files to ${SYSTEM}/etc/terminfo"
-	install "/system/etc/terminfo" 0755 0644 "${SYSTEM}/etc/terminfo"
+  print "Copying terminfo files to ${SYSTEM}/etc/terminfo"
+  install "/system/etc/terminfo" 0755 0644 "${SYSTEM}/etc/terminfo"
 }
 
 [ -d system/lib ] && {
-	print "Copying 32-bit shared libraries to ${SYSTEM}/lib"
-	install "/system/lib" 0755 0644 "${SYSTEM}/lib"
+  print "Copying 32-bit shared libraries to ${SYSTEM}/lib"
+  install "/system/lib" 0755 0644 "${SYSTEM}/lib"
 }
 
 [ -d system/lib64 ] && {
-	print "Copying 64-bit shared libraries to ${SYSTEM}/lib64"
-	install "/system/lib64" 0755 0644 "${SYSTEM}/lib64"
+  print "Copying 64-bit shared libraries to ${SYSTEM}/lib64"
+  install "/system/lib64" 0755 0644 "${SYSTEM}/lib64"
 }
 
 [ -d system/bin ] && {
-	print "Installing ${SYSTEM}/bin binaries"
-	install "/system/bin" 0755 0755 "${SYSTEM}/bin"
+  print "Installing ${SYSTEM}/bin binaries"
+  install "/system/bin" 0755 0755 "${SYSTEM}/bin"
 }
 
 [ -d system/xbin ] && {
-	print "Installing ${SYSTEM}/xbin binaries"
+  print "Installing ${SYSTEM}/xbin binaries"
         [ -d ${SYSTEM}/xbin ] || mkdir -p ${SYSTEM}/xbin
-	install "/system/xbin" 0755 0755 "${SYSTEM}/xbin"
+  install "/system/xbin" 0755 0755 "${SYSTEM}/xbin"
 }
 
 [ -d data/local ] && {
-	print "Copying additional files to /data/local"
-	install "/data/local" 0755 0644
+  print "Copying additional files to /data/local"
+  install "/data/local" 0755 0644
 }
 
 [ -d system/etc/init.d ] && {
-	print "Installing init.d scripts"
-	install "/system/etc/init.d" 0755 0755 "${SYSTEM}/etc/init.d"
-	# Create userinit.d and userinit.sh if they don't already exist
-	mkdir -p "/data/local/userinit.d"
-	setperm 0755 0755 "/data/local/userinit.d"
-	[ -f "/data/local/userinit.sh" ] || echo "#!/system/bin/sh" > "/data/local/userinit.sh"
-	chmod 0755 "/data/local/userinit.sh"
+  print "Installing init.d scripts"
+  install "/system/etc/init.d" 0755 0755 "${SYSTEM}/etc/init.d"
+  # Create userinit.d and userinit.sh if they don't already exist
+  mkdir -p "/data/local/userinit.d"
+  setperm 0755 0755 "/data/local/userinit.d"
+  [ -f "/data/local/userinit.sh" ] || echo "#!/system/bin/sh" > "/data/local/userinit.sh"
+  chmod 0755 "/data/local/userinit.sh"
 }
  
 [ -d system/addon.d/80-nethunter.sh ] && {
-		print "Installing ${SYSTEM}/addon.d backup scripts"
-	install "/system/80-nethunter.sh" 0755 0755 "${SYSTEM}/80-nethunter.sh"
+    print "Installing ${SYSTEM}/addon.d backup scripts"
+  install "/system/80-nethunter.sh" 0755 0755 "${SYSTEM}/80-nethunter.sh"
 }
 
 print "Symlinking Kali boot scripts"
@@ -638,8 +638,8 @@ symlink "/data/data/com.offsec.nethunter/files/scripts/killkali" "${SYSTEM}/bin/
 progress 0.8
 
 [ -d "$patchtmp" ] && {
-	print "Running kernel installer..."
-	sh "$patchtmp/META-INF/com/google/android/update-binary"
+  print "Running kernel installer..."
+  sh "$patchtmp/META-INF/com/google/android/update-binary"
         # setup environment again (all are restored by boot-patcher)
         setup_env
 }
